name: new-post-tests

services:
  mongo-test:
    image: mongo:8
    container_name: new-post-mongo-test
    ports:
      - "27018:27017"
    volumes:
      - mongo_test_data:/data/db

  back-test:
    build:
      context: ./back
      dockerfile: Dockerfile.test
    container_name: new-post-back-test
    depends_on:
      - mongo-test
    env_file:
      - ./back/.test.env
    environment:
      NODE_ENV: test
      MONGO_DB_URL: mongodb://mongo-test:27017/new-post-test
      PORT: 8010
    ports:
      - "8010:8010"

  front-test:
    build:
      context: ./front
      dockerfile: Dockerfile.test
    container_name: new-post-front-test
    depends_on:
      - back-test
    environment:
      NODE_ENV: test
      PORT: 5183
      VITE_API_URL: http://back-test:8010
    ports:
      - "5183:5183"

  e2e:
    build:
      context: ./tests
      dockerfile: Dockerfile.e2e
    container_name: new-post-e2e
    depends_on:
      - front-test
    environment:
      DOCKER_E2E: "true"
      HEADLESS: "true"
      BASE_URL: "http://front-test:5183"

volumes:
  mongo_test_data:
