FROM ghcr.io/puppeteer/puppeteer:22.12.1

USER root

# Обновляем Node.js до 22.x (через NodeSource)
RUN apt-get update \
 && apt-get install -y --no-install-recommends curl ca-certificates gnupg \
 && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
 && apt-get install -y --no-install-recommends nodejs \
 && node -v && npm -v \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

USER pptruser

WORKDIR /work/tests

COPY package*.json ./
RUN npm ci

COPY . .

ENV DOCKER_E2E=true
ENV HEADLESS=true
ENV BASE_URL=http://front-test:5183

CMD sh -lc "npx wait-on --timeout 180000 --interval 500 $BASE_URL && npm run test"
