# --------- build stage ----------
FROM node:22-alpine AS build

WORKDIR /usr/src/back

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build


# --------- production stage ----------
FROM node:22-alpine AS prod

WORKDIR /usr/src/back

ENV NODE_ENV=production

COPY package*.json ./

RUN npm ci --omit=dev

COPY --from=build /usr/src/back/dist ./dist

COPY --from=build /usr/src/back/public ./dist/public

RUN mkdir -p dist/public/uploads/social dist/public/company-files

EXPOSE 8000

CMD ["npm", "run", "start"]
