FROM node:22-bookworm-slim

WORKDIR /usr/src/back

# зависимости отдельно — чтобы кешировалось
COPY package*.json ./
RUN npm ci --include=dev

# код
COPY . .

ENV NODE_ENV=test
ENV PORT=8010

# важно: Mongo URL ты всё равно задаёшь из compose
CMD sh -lc "npm run seed:test && npm run start:test"
