import mongoose from 'mongoose';
import config from './config';
import Admin from './models/Admin';
import { randomUUID } from 'node:crypto';
import Parcel from './models/Parcel';
import Contact from './models/Contact';
import Office from './models/Office';

const run = async () => {
  await mongoose.connect(config.db);
  const db = mongoose.connection;

  try {
    await db.dropCollection('admins');
    await db.dropCollection('parcels');
    await db.dropCollection('contacts');
    await db.dropCollection('offices');
  } catch (e) {
    console.log('No collection, skipping', e);
  }

  await Admin.create([
    {
      email: 'AdminNum1@gmail.com',
      password: 'Qwerty123',
      token: randomUUID(),
      role: 'superAdmin',
      displayName: 'Main Admin',
    },
    {
      email: 'AdminNum2@gmail.com',
      password: 'Qwerty123',
      token: randomUUID(),
      role: 'admin',
      displayName: 'Some Admin',
    },
    {
      email: 'AdminNum3@gmail.com',
      password: 'Qwerty123',
      token: randomUUID(),
      role: 'admin',
      displayName: 'Post Admin',
    },
    {
      email: 'AdminNum4@gmail.com',
      password: 'Qwerty123',
      token: randomUUID(),
      role: 'admin',
      displayName: 'Post Admin',
    },
    {
      email: 'AdminNum5@gmail.com',
      password: 'Qwerty123',
      token: randomUUID(),
      role: 'admin',
      displayName: 'Post Admin',
    },
  ]);

  const [senderOne, recipientOne, senderTwo, recipientTwo] =
    await Contact.create(
      {
        fullName: 'Иванов Петр Сергеевич',
        phoneNumber: '+996 732 274 412',
        email: 'sender1@gmail.com',
        address: 'г. Бишкек, ул. Чуй 123',
        description: 'Одежда и обувь',
        inn_passport: '761238476',
        type: 'sender',
      },
      {
        fullName: 'Сидоров Женя Александрович',
        phoneNumber: '+996 500 274 458',
        email: 'recipient1@gmail.com',
        address: 'г. Москва, ул. Ленина 45',
        description: 'Одежда и обувь',
        inn_passport: '987123948',
        type: 'recipient',
      },
      {
        fullName: 'Калиев Арсен Нурланович',
        phoneNumber: '+996 500 987 454',
        email: 'sender2@gmail.com',
        address: 'г. Ош, ул. Московская 67',
        description: 'Электроника',
        inn_passport: '98217341232',
        type: 'sender',
      },
      {
        fullName: 'Петрова Алина Дмитриевна',
        phoneNumber: '+996 557 890 223',
        email: 'recipient2@gmail.com',
        address: 'г. Санкт-Петербург, Невский пр. 89',
        description: 'Электроника',
        inn_passport: '01293547',
        type: 'recipient',
      }
    );

  await Parcel.create([
    {
      trackingNumber: 'KGZ-000001',
      partnerTrackingNumber: 'LSDFKJEWXOXS',
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: 'Бишкек',
      destinationCity: 'Москва',
      distributionCenter: 'МСК',
      status: 'created',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'pickup',
      weight: 0.6,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000002',
      partnerTrackingNumber: 'PLKJHGFDSA',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'accepted',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'pickup',
      partnerType: 'E-Kit',
      weight: 1.25,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000003',
      partnerTrackingNumber: 'TEST123456',
      sender: senderOne._id,
      recipient: recipientTwo._id,
      originCity: 'Бишкек',
      destinationCity: 'Ош',
      status: 'draft',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.1,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000004',
      partnerTrackingNumber: 'PTN-001-A',
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: 'Бишкек',
      destinationCity: 'Ош',
      status: 'created',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 0.8,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000005',
      partnerTrackingNumber: 'PTN-002-B',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Москва',
      status: 'accepted',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 1.4,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000006',
      partnerTrackingNumber: 'PTN-003-C',
      sender: senderOne._id,
      recipient: recipientTwo._id,
      originCity: 'Бишкек',
      destinationCity: 'Санкт-Петербург',
      status: 'draft',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 3.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000007',
      partnerTrackingNumber: 'PTN-004-D',
      sender: senderTwo._id,
      recipient: recipientOne._id,
      originCity: 'Ош',
      destinationCity: 'Москва',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 0.55,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000008',
      partnerTrackingNumber: 'PTN-005-E',
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: 'Бишкек',
      destinationCity: 'Ош',
      status: 'accepted',
      isPaid: true,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 1.1,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000009',
      partnerTrackingNumber: 'PTN-006-F',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Москва',
      status: 'created',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 1.9,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000010',
      partnerTrackingNumber: 'PTN-007-G',
      sender: senderOne._id,
      recipient: recipientTwo._id,
      originCity: 'Бишкек',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 0.7,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000011',
      partnerTrackingNumber: 'PTN-008-H',
      sender: senderTwo._id,
      recipient: recipientOne._id,
      originCity: 'Ош',
      destinationCity: 'Бишкек',
      status: 'draft',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.0,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000012',
      partnerTrackingNumber: 'PTN-009-I',
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: 'Бишкек',
      destinationCity: 'Москва',
      status: 'created',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 1.3,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000013',
      partnerTrackingNumber: 'PTN-010-J',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'accepted',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 4.1,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000014',
      partnerTrackingNumber: 'PTN-011-K',
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: 'Бишкек',
      destinationCity: 'Ош',
      status: 'created',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 0.9,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000015',
      partnerTrackingNumber: 'PTN-012-L',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'ОШ',
      destinationCity: 'Москва',
      status: 'draft',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.5,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000016',
      partnerTrackingNumber: 'PTN-013-M',
      sender: senderOne._id,
      recipient: recipientTwo._id,
      originCity: 'Бишкек',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 1.45,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000017',
      partnerTrackingNumber: 'PTN-014-N',
      sender: senderTwo._id,
      recipient: recipientOne._id,
      originCity: 'Ош',
      destinationCity: 'Бишкек',
      status: 'accepted',
      isPaid: true,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 3.3,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000018',
      partnerTrackingNumber: 'PTN-015-O',
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: 'Бишкек',
      destinationCity: 'Ош',
      status: 'created',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 0.75,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000019',
      partnerTrackingNumber: 'PTN-016-P',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Москва',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 1.6,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000020',
      partnerTrackingNumber: 'PTN-017-Q',
      sender: senderOne._id,
      recipient: recipientTwo._id,
      originCity: 'Бишкек',
      destinationCity: 'Санкт-Петербург',
      status: 'draft',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.9,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000021',
      partnerTrackingNumber: 'PTN-018-R',
      sender: senderTwo._id,
      recipient: recipientOne._id,
      originCity: 'Ош',
      destinationCity: 'Москва',
      status: 'accepted',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 3.7,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000022',
      partnerTrackingNumber: 'PTN-019-S',
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: 'Бишкек',
      destinationCity: 'Ош',
      status: 'created',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 1.0,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000023',
      partnerTrackingNumber: 'PTN-020-T',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000024',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000026',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000027',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000028',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000029',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000030',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000031',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000032',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000033',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000034',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000035',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000036',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000037',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000038',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000039',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000040',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000044',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000045',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000046',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000047',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000048',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000049',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000050',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000051',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000052',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000053',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000054',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000055',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000056',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000057',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },{
      trackingNumber: 'KGZ-000058',
      partnerTrackingNumber: 'PTN-020-TAFWDDDDS2',
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: 'Ош',
      destinationCity: 'Санкт-Петербург',
      status: 'shipped',
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 2.2,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
    {
      trackingNumber: 'KGZ-000066',
      partnerTrackingNumber: 'PTN-001-A',
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: 'Бишкек',
      destinationCity: 'Ош',
      status: 'created',
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: 'courier',
      partnerType: 'KCE',
      weight: 0.8,
      description: 'Посылка с одеждой',
      inshprice:777,
      price: 777,
    },
  ]);

  const fullHistoryParcel = new Parcel({
    trackingNumber: 'KGZ-000025',
    partnerTrackingNumber: 'FULL-TRACK-001',
    sender: senderOne._id,
    recipient: recipientTwo._id,
    originCity: 'Бишкек',
    destinationCity: 'Москва',
    status: 'delivered',
    isPaid: true,
    partnerStickerReceived: true,
    weight: 2.5,
    inshprice:777,
    price: 777,
    description: 'Полная история посылки',
  });

  await fullHistoryParcel.save();

  await Parcel.updateOne(
    {_id: fullHistoryParcel._id},
    {
      $set: {
        draftedAt: new Date('2025-11-15T10:00:00Z'),
        createdAt: new Date('2025-11-15T11:30:00Z'),
        acceptedAt: new Date('2025-11-16T09:00:00Z'),
        shippedAt: new Date('2025-11-16T14:00:00Z'),
        inCountryAt: new Date('2025-11-17T08:00:00Z'),
        inCityAt: new Date('2025-11-18T10:00:00Z'),
        atPickupPointAt: new Date('2025-11-18T15:00:00Z'),
        deliveredAt: new Date('2025-11-19T11:00:00Z'),
      },
    }
  );

  await Office.create([
    {
      name: 'Новая почта',
      city: 'bishkek',
      label: 'Бишкек',
      address: 'Улица Льва Толстого, 24/1',
      worktime: 'Ежедневно с 09:00 до 20:00',
      phone: '+996778465557',
      mapUrl: 'https://go.2gis.com/sgcnj'
    },
    {
      name: 'Новая почта',
      city: 'bishkek',
      label: 'Бишкек',
      address: 'ТЦ Дордой Плаза Улица Ибраимова, 115/2 - 1 этаж',
      worktime: 'Пн — Пт 10:00–19:00 \n Перерыв 13:00–14:00',
      phone: '+996778465557',
      mapUrl: 'https://go.2gis.com/8wVAq'
    },
    {
      name: 'Новая почта',
      city: 'manas',
      label: 'Манас',
      address: 'Проспект Тумонбая Байзакова, 18',
      worktime: 'Пн — Пт 09:00–18:00',
      phone: '+996778465557',
      mapUrl: 'https://go.2gis.com/2uwVo'
    },
    {
      name: 'Новая почта',
      label: 'Каракол',
      city: 'karakol',
      address: 'Улица Торгоева, 35',
      worktime: 'Пн — Пт 09:00–19:00',
      phone: '+996778465557',
      mapUrl: 'https://go.2gis.com/ushEH'
    },
    {
      name: 'Новая почта',
      label: 'ОШ',
      city: 'osh',
      address: 'ЖК "Сулайман Тоо" Улица Курманжан датка, 121в1 этаж',
      worktime: 'Пн — Пт 09:00–18:00',
      phone: '+996778465557',
      mapUrl: 'https://go.2gis.com/DJSnL'
    }
  ]);

  await db.close();
};

run().catch(console.error);
