import mongoose from "mongoose";
import config from "./config";
import Admin from "./models/Admin";
import { randomUUID } from "node:crypto";
import Parcel from "./models/Parcel";
import Contact from "./models/Contact";

const run = async () => {
  await mongoose.connect(config.db);
  const db = mongoose.connection;

  try {
    await db.dropCollection("admins");
    await db.dropCollection("parcels");
    await db.dropCollection("contacts");
  } catch (e) {
    console.log("No collection, skipping", e);
  }

  await Admin.create([
    {
      email: "AdminNum1@gmail.com",
      password: "Qwerty123",
      token: randomUUID(),
      role: "superAdmin",
      displayName: "Main Admin",
    },
    {
      email: "AdminNum2@gmail.com",
      password: "Qwerty123",
      token: randomUUID(),
      role: "admin",
      displayName: "Some Admin",
    },
    {
      email: "AdminNum3@gmail.com",
      password: "Qwerty123",
      token: randomUUID(),
      role: "admin",
      displayName: "Post Admin",
    },
    {
      email: "AdminNum4@gmail.com",
      password: "Qwerty123",
      token: randomUUID(),
      role: "admin",
      displayName: "Post Admin",
    },
    {
      email: "AdminNum5@gmail.com",
      password: "Qwerty123",
      token: randomUUID(),
      role: "admin",
      displayName: "Post Admin",
    },
  ]);

  const [senderOne, recipientOne, senderTwo, recipientTwo] =
    await Contact.create(
      {
        fullName: "Иванов Петр Сергеевич",
        phoneNumber: "+996 732 274 412",
        email: "sender1@gmail.com",
        address: "г. Бишкек, ул. Чуй 123",
        description: "Одежда и обувь",
        inn_passport: "761238476",
        type: "sender",
      },
      {
        fullName: "Сидоров Женя Александрович",
        phoneNumber: "+996 500 274 458",
        email: "recipient1@gmail.com",
        address: "г. Москва, ул. Ленина 45",
        description: "Одежда и обувь",
        inn_passport: "987123948",
        type: "recipient",
      },
      {
        fullName: "Калиев Арсен Нурланович",
        phoneNumber: "+996 500 987 454",
        email: "sender2@gmail.com",
        address: "г. Ош, ул. Московская 67",
        description: "Электроника",
        inn_passport: "98217341232",
        type: "sender",
      },
      {
        fullName: "Петрова Алина Дмитриевна",
        phoneNumber: "+996 557 890 223",
        email: "recipient2@gmail.com",
        address: "г. Санкт-Петербург, Невский пр. 89",
        description: "Электроника",
        inn_passport: "01293547",
        type: "recipient",
      }
    );

  await Parcel.create([
    {
      trackingNumber: "KGZ-312-SLFKDJEWSL",
      partnerTrackingNumber: "LSDFKJEWXOXS",
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: "Бишкек",
      destinationCity: "Москва",
      status: "created",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "pickup",
      partnerType: "E-Kit",
      weight: 0.6,
    },
    {
      trackingNumber: "KGZ-478-QWERTYUIOP 2",
      partnerTrackingNumber: "PLKJHGFDSA",
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: "Ош",
      destinationCity: "Санкт-Петербург",
      status: "accepted",
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: "pickup",
      partnerType: "E-Kit",
      weight: 1.25,
    },
    {
      trackingNumber: "KGZ-999-TESTTRACK 3",
      partnerTrackingNumber: "TEST123456",
      sender: senderOne._id,
      recipient: recipientTwo._id,
      originCity: "Бишкек",
      destinationCity: "Ош",
      status: "draft",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 2.1,
    },
    {
      trackingNumber: "KGZ-001-TESTA 4",
      partnerTrackingNumber: "PTN-001-A",
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: "Бишкек",
      destinationCity: "Ош",
      status: "created",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 0.8,
    },
    {
      trackingNumber: "KGZ-002-TESTB 5",
      partnerTrackingNumber: "PTN-002-B",
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: "Ош",
      destinationCity: "Москва",
      status: "accepted",
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 1.4,
    },
    {
      trackingNumber: "KGZ-003-TESTC 6",
      partnerTrackingNumber: "PTN-003-C",
      sender: senderOne._id,
      recipient: recipientTwo._id,
      originCity: "Бишкек",
      destinationCity: "Санкт-Петербург",
      status: "draft",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 3.2,
    },
    {
      trackingNumber: "KGZ-004-TESTD 7",
      partnerTrackingNumber: "PTN-004-D",
      sender: senderTwo._id,
      recipient: recipientOne._id,
      originCity: "Ош",
      destinationCity: "Москва",
      status: "shipped",
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 0.55,
    },
    {
      trackingNumber: "KGZ-005-TESTE 8",
      partnerTrackingNumber: "PTN-005-E",
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: "Бишкек",
      destinationCity: "Ош",
      status: "accepted",
      isPaid: true,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 1.1,
    },
    {
      trackingNumber: "KGZ-006-TESTF 9",
      partnerTrackingNumber: "PTN-006-F",
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: "Ош",
      destinationCity: "Москва",
      status: "created",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 1.9,
    },
    {
      trackingNumber: "KGZ-007-TESTG10",
      partnerTrackingNumber: "PTN-007-G",
      sender: senderOne._id,
      recipient: recipientTwo._id,
      originCity: "Бишкек",
      destinationCity: "Санкт-Петербург",
      status: "shipped",
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 0.7,
    },
    {
      trackingNumber: "KGZ-008-TESTH11",
      partnerTrackingNumber: "PTN-008-H",
      sender: senderTwo._id,
      recipient: recipientOne._id,
      originCity: "Ош",
      destinationCity: "Бишкек",
      status: "draft",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 2.0,
    },
    {
      trackingNumber: "KGZ-009-TESTI12",
      partnerTrackingNumber: "PTN-009-I",
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: "Бишкек",
      destinationCity: "Москва",
      status: "created",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 1.3,
    },
    {
      trackingNumber: "KGZ-010-TESTJ13",
      partnerTrackingNumber: "PTN-010-J",
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: "Ош",
      destinationCity: "Санкт-Петербург",
      status: "accepted",
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 4.1,
    },
    {
      trackingNumber: "KGZ-011-TESTK14",
      partnerTrackingNumber: "PTN-011-K",
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: "Бишкек",
      destinationCity: "Ош",
      status: "created",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 0.9,
    },
    {
      trackingNumber: "KGZ-012-TESTL15",
      partnerTrackingNumber: "PTN-012-L",
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: "ОШ",
      destinationCity: "Москва",
      status: "draft",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 2.5,
    },
    {
      trackingNumber: "KGZ-013-TESTM16",
      partnerTrackingNumber: "PTN-013-M",
      sender: senderOne._id,
      recipient: recipientTwo._id,
      originCity: "Бишкек",
      destinationCity: "Санкт-Петербург",
      status: "shipped",
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 1.45,
    },
    {
      trackingNumber: "KGZ-014-TESTN17",
      partnerTrackingNumber: "PTN-014-N",
      sender: senderTwo._id,
      recipient: recipientOne._id,
      originCity: "Ош",
      destinationCity: "Бишкек",
      status: "accepted",
      isPaid: true,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 3.3,
    },
    {
      trackingNumber: "KGZ-015-TESTO18",
      partnerTrackingNumber: "PTN-015-O",
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: "Бишкек",
      destinationCity: "Ош",
      status: "created",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 0.75,
    },
    {
      trackingNumber: "KGZ-016-TESTP19",
      partnerTrackingNumber: "PTN-016-P",
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: "Ош",
      destinationCity: "Москва",
      status: "shipped",
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 1.6,
    },
    {
      trackingNumber: "KGZ-017-TESTQ20",
      partnerTrackingNumber: "PTN-017-Q",
      sender: senderOne._id,
      recipient: recipientTwo._id,
      originCity: "Бишкек",
      destinationCity: "Санкт-Петербург",
      status: "draft",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 2.9,
    },
    {
      trackingNumber: "KGZ-018-TESTR21",
      partnerTrackingNumber: "PTN-018-R",
      sender: senderTwo._id,
      recipient: recipientOne._id,
      originCity: "Ош",
      destinationCity: "Москва",
      status: "accepted",
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 3.7,
    },
    {
      trackingNumber: "KGZ-019-TESTS22",
      partnerTrackingNumber: "PTN-019-S",
      sender: senderOne._id,
      recipient: recipientOne._id,
      originCity: "Бишкек",
      destinationCity: "Ош",
      status: "created",
      isPaid: false,
      partnerStickerReceived: false,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 1.0,
    },
    {
      trackingNumber: "KGZ-020-TESTT23",
      partnerTrackingNumber: "PTN-020-T",
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: "Ош",
      destinationCity: "Санкт-Петербург",
      status: "shipped",
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 2.2,
    },
    {
      trackingNumber: "KGZ-020-A1B2C3D4F5",
      partnerTrackingNumber: "PTN-020-TAFWDDDDS2",
      sender: senderTwo._id,
      recipient: recipientTwo._id,
      originCity: "Ош",
      destinationCity: "Санкт-Петербург",
      status: "shipped",
      isPaid: true,
      partnerStickerReceived: true,
      deliveryType: "courier",
      partnerType: "KCE",
      weight: 2.2,
    },
  ]);

  const fullHistoryParcel = new Parcel({
    trackingNumber: "KGZ-FULL-HISTORY-2025",
    partnerTrackingNumber: "FULL-TRACK-001",
    sender: senderOne._id,
    recipient: recipientTwo._id,
    originCity: "Бишкек",
    destinationCity: "Москва",
    status: "delivered",
    isPaid: true,
    partnerStickerReceived: true,
    weight: 2.5,
  });

  await fullHistoryParcel.save();

  await Parcel.updateOne(
    { _id: fullHistoryParcel._id },
    {
      $set: {
        draftedAt: new Date("2025-11-15T10:00:00Z"),
        createdAt: new Date("2025-11-15T11:30:00Z"),
        acceptedAt: new Date("2025-11-16T09:00:00Z"),
        shippedAt: new Date("2025-11-16T14:00:00Z"),
        inCountryAt: new Date("2025-11-17T08:00:00Z"),
        inCityAt: new Date("2025-11-18T10:00:00Z"),
        atPickupPointAt: new Date("2025-11-18T15:00:00Z"),
        deliveredAt: new Date("2025-11-19T11:00:00Z"),
      },
    }
  );

  await db.close();
};

run().catch(console.error);
