# --------- build stage ----------
FROM node:22-alpine AS build

WORKDIR /usr/src/front

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build


# --------- nginx stage ----------
FROM nginx:alpine AS prod

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /usr/src/front/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
