FROM node:22-bookworm-slim

WORKDIR /usr/src/front

COPY package*.json ./
RUN npm ci --include=dev

COPY . .

ENV NODE_ENV=test
ENV PORT=5183
ENV VITE_API_URL=http://back-test:8010

CMD sh -lc "npm run start:test"
